version: "3.8"

services:
  api:
    build: .
    container_name: blm-spider-api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped