openapi: 3.0.3
info:
  title: BLM Campsites API
  version: 1.0.0
  description: API for accessing BLM dispersed campsite data.
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://blm-spider.onrender.com/
    description: Production server
paths:
  /api/v1/campsites:
    get:
      summary: Retrieve all campsites
      description: Returns a list of BLM campsites. Supports optional filtering by state and pagination.
      parameters:
      - in: query
        name: state
        schema:
          type: string
        description: Filter campsites by U.S. state
      - in: query
        name: limit
        schema:
          type: integer
          minimum: 1
        description: Maximum number of results to return
      - in: query
        name: offset
        schema:
          type: integer
          minimum: 0
        description: Number of results to skip before starting to return results
      responses:
        '200':
          description: A list of campsites
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Campsite'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/campsites/{id}:
    get:
      summary: Get a single campsite by ID
      description: Retrieves detailed information for a specific campsite.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: The unique ID of the campsite
      responses:
        '200':
          description: Campsite found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Campsite'
        '404':
          description: Campsite not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Campsite:
      type: object
      required:
      - id
      - name
      - url
      - lat
      - lng
      - state
      - mapLink
      - source
      properties:
        id:
          type: string
          description: Unique campsite identifier
        name:
          type: string
          description: Name of the campsite
        url:
          type: string
          description: Source webpage URL
        lat:
          type: number
          description: Latitude coordinate
        lng:
          type: number
          description: Longitude coordinate
        state:
          type: string
          description: U.S. state abbreviation
        mapLink:
          type: string
          description: URL for an embeddable map of the campsite location
        description:
          type: string
          nullable: true
          description: Overview or description of the campsite
        directions:
          type: string
          nullable: true
          description: Directions to the campsite
        activities:
          type: array
          items:
            type: string
          nullable: true
          description: Activities available at the campsite
        campgrounds:
          type: array
          items:
            type: string
          nullable: true
          description: Associated campground names
        wildlife:
          type: array
          items:
            type: string
          nullable: true
          description: Common wildlife in the area
        fees:
          type: string
          nullable: true
          description: Fee information, if any
        stayLimit:
          type: string
          nullable: true
          description: Maximum duration allowed for camping
        images:
          type: array
          items:
            $ref: '#/components/schemas/CampsiteImage'
          nullable: true
          description: Photos of the campsite
        source:
          type: string
          enum: [ BLM ]
          description: Data source for the campsite

    CampsiteImage:
      type: object
      required:
      - src
      properties:
        src:
          type: string
          description: Image URL
        alt:
          type: string
          nullable: true
          description: Alternative text
        credit:
          type: string
          nullable: true
          description: Image credit

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
