name: Docker Build

on:
  pull_request:
    paths:
    - 'Dockerfile'
    - '**/package.json'
    - '**/package-lock.json'
    - '.github/workflows/docker.yml'
    - '**/*.ts'
    - '**/*.js'
    - '**/*.json'
    - '**/*.yml'
    - '**/*.yaml'
  push:
    branches:
    - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t blm-spider .

    - name: Test container starts
      run: |
        docker run -d --name blm-spider-test -p 8080:8080 blm-spider
        sleep 10
        docker ps | grep blm-spider-test

    - name: Clean up
      if: always()
      run: docker rm -f blm-spider-test
